server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

